pipeline {
    agent any
    tools {
        nodejs 'node'
        dockerTool 'docker'
    }

    stages {
        stage('Clone') {
            steps {
                git branch: 'main', url: 'https://github.com/skynetskander/Documentation.git'
            }
        }

        stage('Install dependency') {
            steps {
                nodejs('node') {
                    npm 'install'
                }
            }
        }
        stage('SonarQube Analyzes') {
            steps {
                echo "Testing..."
                // Add test steps here
            }
        }
        stage('Docker Build') {
            steps {
                echo "Building..."
                sh 'docker build -t my-docker-image:v1 .'
            }
        }



        stage('Push docker image to Nexus') {
            steps {
                dockerPushToNexus('docker build -t my-docker-image:v1 .')
            
            }
        }
        
        stage('Deploy') {
            steps {
                echo "Deploying..."
                // Add deployment steps here
            }
        }
    }

    post {
        success {
            echo 'Pipeline succeeded!'
            // Additional actions to perform if the pipeline succeeds
        }

        failure {
            echo 'Pipeline failed!'
            // Additional actions to perform if the pipeline fails
        }
    }
}